export enum StatusProps {
    PENDENTE = 'PENDENTE',
    CONCLUIDO = 'CONCLUIDO',
    AGUARDANDO = 'AGUARDANDO',
    SUCESSO = 'SUCESSO',
    ATENDIDO = 'ATENDIDO',
    REQ_CANCELAMENTO = 'REQ_CANCELAMENTO',
    AGENDADO = 'AGENDADO',
    CANCELADO = 'CANCELADO',
}
